# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 11:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('mytishy', django.db.models.manager.Manager()),
            ],
        ),
    ]
