# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('decription', models.CharField(blank=True, max_length=1024, null=True)),
                ('format', models.CharField(blank=True, max_length=1024, null=True)),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_shared', models.BooleanField(default=False)),
            ],
        ),
    ]
