# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='records/'),
        ),
    ]
