# Generated by Django 2.0.5 on 2018-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180522_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='link_ext',
            field=models.URLField(blank=True),
        ),
    ]
