# Generated by Django 2.0.5 on 2018-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_link_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
