# Generated by Django 2.0.5 on 2018-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_record_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
